apiVersion: v1
kind: Namespace
metadata: { name: ldl-data }
---
apiVersion: v1
kind: Namespace
metadata: { name: ldl-platform }
---
apiVersion: v1
kind: Namespace
metadata: { name: ldl-observability }
---
apiVersion: v1
kind: Namespace
metadata: { name: ldl-apps }
